[package]
name = "sled-entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.34.7"
serde = "1"
serde_derive = "1"
serde_json = "1"
bincode = "1.3.3"
paste = "1.0"
hashers = "1"